-- UniFlow Database (MySQL) — Prisma-managed
--
-- Source of truth:
--   - backend/prisma/schema.prisma
--   - backend/prisma/migrations/
--
-- This file is intentionally kept as the single `database.sql` reference in the repo.
-- It is NOT hand-maintained and is not required for normal development.
--
-- Recommended setup (dev/prod):
--   npx prisma migrate deploy
--   npx prisma db seed
--
-- If you need a raw SQL snapshot from the current Prisma schema, generate it:
--   npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script > database.sql
